// ------------------------------------------------------------------------------
// <auto-generated>
//     Clase proxy de Crystal Reports para Rpt_BalanceAntiguedad.
//
//     INSTRUCCIONES PARA CREAR EL REPORTE EN VISUAL STUDIO:
//     1. Agregar un nuevo elemento "Crystal Reports" al proyecto Capa_Vista_Ventas
//        con el nombre "Rpt_BalanceAntiguedad.rpt".
//     2. Elegir "Using the Report Wizard" > "Standard".
//     3. Agregar como origen de datos un DataSet / ADO.NET Dataset que contenga
//        las columnas que devuelve sp_BalanceAntiguedadCxC:
//          Pk_Id_Cliente, NombreCliente, NIT, IdCxC, NoVenta,
//          FechaDeuda, FechaVencimiento, MontoTotal, TotalPagado,
//          SaldoPendiente, DiasVencidos, RangoAntiguedad,
//          MontoCorriente, Monto1a30, Monto31a60, Monto61a90, MontoMas90
//     4. Agrupar por NombreCliente (Group Header/Footer).
//     5. Colocar en el Detail las columnas de documento y saldo por rango.
//     6. Agregar sumarios (Sum) por grupo y gran total para las columnas de monto.
//     7. En el Report Header añadir dos parámetros de tipo Date:
//        {?FechaDesde} y {?FechaHasta} para mostrar el encabezado del filtro.
//     8. Guardar; Visual Studio regenerará automáticamente este archivo.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Capa_Vista_Ventas
{
    using System.ComponentModel;
    using CrystalDecisions.Shared;
    using CrystalDecisions.ReportSource;
    using CrystalDecisions.CrystalReports.Engine;

    public class Rpt_BalanceAntiguedad : ReportClass
    {
        public Rpt_BalanceAntiguedad() { }

        public override string ResourceName
        {
            get { return "Rpt_BalanceAntiguedad.rpt"; }
            set { }
        }

        public override bool NewGenerator
        {
            get { return true; }
            set { }
        }

        public override string FullResourceName
        {
            get { return "Capa_Vista_Ventas.Rpt_BalanceAntiguedad.rpt"; }
            set { }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.CrystalReports.Engine.Section Section1
        {
            get { return this.ReportDefinition.Sections[0]; }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.CrystalReports.Engine.Section Section2
        {
            get { return this.ReportDefinition.Sections[1]; }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.CrystalReports.Engine.Section Section3
        {
            get { return this.ReportDefinition.Sections[2]; }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.CrystalReports.Engine.Section Section4
        {
            get { return this.ReportDefinition.Sections[3]; }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public CrystalDecisions.CrystalReports.Engine.Section Section5
        {
            get { return this.ReportDefinition.Sections[4]; }
        }
    }

    [System.Drawing.ToolboxBitmapAttribute(typeof(CrystalDecisions.Shared.ExportOptions), "report.bmp")]
    public class CachedRpt_BalanceAntiguedad : System.ComponentModel.Component, ICachedReport
    {
        public CachedRpt_BalanceAntiguedad() { }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public virtual bool IsCacheable
        {
            get { return true; }
            set { }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public virtual bool ShareDBLogonInfo
        {
            get { return false; }
            set { }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public virtual System.TimeSpan CacheTimeOut
        {
            get { return CachedReportConstants.DEFAULT_TIMEOUT; }
            set { }
        }

        public virtual CrystalDecisions.CrystalReports.Engine.ReportDocument CreateReport()
        {
            Rpt_BalanceAntiguedad rpt = new Rpt_BalanceAntiguedad();
            rpt.Site = this.Site;
            return rpt;
        }

        public virtual string GetCustomizedCacheKey(RequestContext request)
        {
            return null;
        }
    }
}
